config/routes.rb
Drinkboard::Application.routes.draw do
  
  root to: 'users#new'
  resources :locations

  resources :employees
  match "/invite/:id" => "invite#show"
  
  resources :orders
  resources :redeems
  resources :gifts do
    collection do
      get  'buy'
      get  'activity'
      get  'browse'
      post 'browse_with_contact'
      post 'browse_with_location'
      post 'choose_from_menu'
      post 'choose_from_contacts'
      post 'bill'
      get  'past'
    end
    member do
      get 'detail'
      get 'completed'
    end
  end

  resources :providers 
  
  
  resources :merchants do
    member do
      get 'past_orders'
      get 'detail'
      get 'customers'
      get 'orders'
      get 'order'
      get 'completed'
      get 'staff'
    end
  end
  
  resources :items
  resources :menus
  resources :menu_strings

  resources :connections, only: [:create, :destroy]
  resources :sessions,    only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  resources :admins, only: [:new, :create, :destroy]

  
  match 'app/create_account',   to: 'iphone#create_account',   via: :post
  match 'app/login',            to: 'iphone#login',            via: :post
  match 'app/gifts',            to: 'iphone#gifts',            via: :post
  match 'app/buys',             to: 'iphone#buys',             via: :post
  match 'app/activity',         to: 'iphone#activity',         via: :post
  match 'app/provider',         to: 'iphone#provider',         via: :post
  match 'app/locations',        to: 'iphone#locations',        via: :post
  match 'app/buy_gift',         to: 'iphone#create_gift',      via: :post
  match 'app/redeem',           to: 'iphone#create_redeem',    via: :post
  match 'app/order',            to: 'iphone#create_order',     via: :post
  match 'app/users',            to: 'iphone#drinkboard_users', via: :post
  match 'app/photo',            to: 'iphone#update_photo',     via: :post 
  match 'app/merchant/active',  to: 'iphone#active_orders',    via: :post
  match 'app/merchant/complete',to: 'iphone#completed_orders', via: :post
  
  match '/about',       to: 'home#about'
  match '/contact',     to: 'home#contact'
  match '/home',        to: 'home#index'
  match '/learn',       to: 'home#learn'
  match '/news',        to: 'home#news'
  
  match '/facebook/oauth',    to: 'oAuth#loginWithFacebook'
  match '/foursquare/oauth',  to: 'oAuth#loginWithFoursquare'
  
  match '/map', to: 'locations#map'
  match '/map/boundary', to: 'locations#mapForUserWithinBoundary'
  
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :users do 
    member do
      get :following, :followers
      get :servercode
      get :crop
    end
  end
  

end

app/models/redeem.rb
# == Schema Information
#
# Table name: redeems
#
#  id                   :integer         not null, primary key
#  gift_id              :integer
#  reply_message        :string(255)
#  redeem_code          :string(255)
#  special_instructions :text
#  created_at           :datetime        not null
#  updated_at           :datetime        not null
#

class Redeem < ActiveRecord::Base
  attr_accessible :gift_id, :redeem_code, :reply_message, :special_instructions
  
  belongs_to      :gift
  has_one         :giver,     :through => :gift
  has_one         :receiver,  :through => :gift
  has_one         :provider,  :through => :gift
  has_one         :order
  
  before_create :create_redeem_code
  after_create  :add_redeem_to_gift
  
  validates :gift_id , presence: true, uniqueness: true
  # redeem must be unique for gift
  
  private

    def create_redeem_code
      self.redeem_code = "%04d" % rand(10000)
    end
    
    def add_redeem_to_gift
      self.gift.update_attributes({status: 'notified', redeem_id: self.id})
    end
end

app/controllers/redeems_controller.rb
class RedeemsController < ApplicationController

  def index
    @redeems = Redeem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @redeems }
    end
  end

  def show
    @redeem   = Redeem.find(params[:id])
    @gift     = @redeem.gift
    @giver    = @redeem.giver
    provider  = @redeem.provider
    @server_codes = provider.server_codes
    @servers  = provider.get_servers
    @order = Order.new(redeem_id: @redeem.id, gift_id: @gift.id, provider_id: provider.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @redeem }
    end
  end

  def new
    #@gift = Gift.find(params[:gift_id])
    @gift = Gift.new
    @redeem = Redeem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @redeem }
    end
  end

  def edit
    @redeem = Redeem.find(params[:id])
  end

  def create
    gift_id = params[:gift_id]
    if @redeem = Redeem.find_by_gift_id(gift_id)
      notice = nil
    else
      @redeem = Redeem.new(gift_id: gift_id)
      notice  = 'Give the code in blue to your server or user the server code by clicking merchant redeem below'
    end
    respond_to do |format|
      if @redeem.save
        if notice
          format.html { redirect_to @redeem, notice: notice }
        else
          format.html { redirect_to @redeem }
        end
        format.json { render json: @redeem, status: :created, location: @redeem }
      else
        format.html { render action: "new" }
        format.json { render json: @redeem.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @redeem = Redeem.find(params[:id])

    respond_to do |format|
      if @redeem.update_attributes(params[:redeem])
        format.html { redirect_to @redeem, notice: 'Redeem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @redeem.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @redeem = Redeem.find(params[:id])
    @redeem.destroy

    respond_to do |format|
      format.html { redirect_to redeems_url }
      format.json { head :no_content }
    end
  end
end

app/views/redeems/_form.html.erb
<!-- Redeems Form -->

<%= form_for(@redeem) do |f| %>
<% if @redeem.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@redeem.errors.count, "error") %> prohibited this redeem from being saved:</h2>
  <ul>
  <% @redeem.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
  <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :gift_id %><br />
  <%= f.number_field :gift_id %>
</div>
<div class="field">
  <%= f.label :reply_message %><br />
  <%= f.text_area :reply_message %>
</div>
<div class="field">
  <%= f.label :redeem_code %><br />
  <%= f.number_field :redeem_code %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/redeems/edit.html.erb
<h2>Editing redeem</h2>

<%= render 'form' %>

<%= link_to 'Show', @redeem %> |
<%= link_to 'Back', redeems_path %>

app/views/redeems/index.html.erb
<!-- Redeems Index -->

<div class="redeemsIndexWrapper">
  <h2>
    <span="h2Highlight">
    Listing redeems
    </span>
  </h2>
  <h2>Gift</h2>
  <h2>Reply message</h2>
  <h2>Redeem code</h2>
  <% @redeems.each do |redeem| %>
  <h2>
    <%= redeem.gift_id %>
  </h2>
  <h2>
    <%= redeem.reply_message %>
  </h2>
  <h2>
    <%= redeem.redeem_code %>
  </h2>
  <h2>
    <%= link_to 'Show', redeem %>
  </h2>
  <h2>
    <%= link_to 'Edit', edit_redeem_path(redeem) %>
  </h2>
  <h2>
    <%= link_to 'Destroy', redeem, confirm: 'Are you sure?', method: :delete %>
  </h2>
  <% end %>
  <h2>
    <%= link_to 'New Redeem', new_redeem_path %>
  </h2>
</div>

app/views/redeems/new.html.erb
<h1>New redeem</h1>

<%= render 'form' %>

<%= link_to 'Back', redeems_path %>

app/views/redeems/show-old.html.erb
<p id="notice"><%= notice %></p>

<%= list_icon_for @giver %> <%= @gift.giver_name %> 

bought you 

<%= @gift.quantity %> <%= @gift.item_name %>

<%= logo_from_id_for @gift.provider_id %>

located at <%= @gift.provider_name %>

<% if @gift.message %>
Message:
<%= @gift.message %>
<% end %>


<%= button_to "Send them a Drink", browse_with_contact_gifts_path(id: @gift.giver_id), :class => "btn" %>
<%= button_to 'Not Now', gifts_path, method: :get %>

Give this code to your server to Redeem: 
<a href="#" class="btn btn-large btn-primary disabled"><%= @redeem.redeem_code %></a>

Server's phone unavailable?
<button type="button" class="btn btn-large btn-success" id="merchant_redeem">
  Enter Server Code
</button>
<div id="servers">
  Choose Your Server
  <% @servers.each do |user| %>
  <div id="<%= user.id %>">
    <%= gravatar_for user %>
    <%= user.username %>
    <%= user.server_code %>
    <button type="button" class="btn choose_server" id="<%= user.id %>" name="<%= user.username %>">
      Choose
    </button>
  </div>
  <% end %>
</div>
<div id="server_code_field">
  <%= simple_form_for @order do |f| %>
  <%= f.error_notification %>
  <% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@order.errors.count, "error") %>.
    </div>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-horizontal">
    <%= f.hidden_field :redeem_id  %>
    <%= f.hidden_field :gift_id  %>
    <%= f.hidden_field :server_id  %>
    <%= f.hidden_field :provider_id  %>
    <%= f.input :server_code, :input_html => { :maxlength => 4 } %>
  </div>
  <%= f.submit "Submit Server Code", :class => "btn" %>
  <% end %>
  <div>
    <button type="button" class="btn btn-large btn-success" id="servers_back_button">
      Choose Another Server
    </button>
  </div>
</div>

<script>
  var a = $('#order_server_id');

  $(function() {
    $('#servers, #server_code_field').hide();
    $('#merchant_redeem').click(function() {
      if (!$(this).hasClass('disabled')) {
        if ($(this).text()=="Enter Server Code") {
          $('#servers').slideDown('fast');
          $(this).text("Hide Servers");
        } else {
          $('#servers').slideUp('fast');
          $(this).text("Enter Server Code");
        } 
      }    
    });
    $('.choose_server').click(function() {
      if ($(this).hasClass('disabled')) {
        $('#server_code_field').slideUp('fast');
        $('.choose_server').removeClass('disabled');
      } else {
        $('#server_code_field').slideDown('fast');
        $('.choose_server').addClass('disabled');
        $('#merchant_redeem').addClass('disabled');
        var currentId = $(this).attr('id');
        addServerInfo(currentId);
      }
    });
    $('#servers_back_button').click(function() {
       $('.choose_server').removeClass('disabled');
       $('#server_code_field').slideUp('slow');
       $('#merchant_redeem').removeClass('disabled');
       removeServerInfo();
    });
  });
  
  function addServerInfo(currentId) {
    // take the server info and place it in the code submit form
    a.val(currentId);
  };
  
  function removeServerInfo() {
    a.val('');
  };
  
  
</script>

app/views/redeems/show.html.erb
<!-- Redeem Drink Main Page (enter server code etc.) -->


<div class="detailWrapper redeemWrapper">
  <div class="profileImage">
    <%= list_icon_for @giver %> 
  </div>
  <h2 class="textTop">
    <span class="h2Highlight"><%= @gift.giver_name %></span>
    bought you 
    <%= @gift.quantity %> 
    <%= @gift.item_name %>
    <% if @gift.message %>
    <%= @gift.message %>
    <% end %>
  </h2>
  <h2 class="providerPic">
    <%= logo_from_id_for @gift.provider_id %>
  </h2>
  <h2 class="textRedeem">
  Redeem them at <br /><span class="h2Highlight"><%= @gift.provider_name %></span>
  </h2> 
  <div class="actionsWrapper">
    <div class="sendDrink">
    <%= button_to "Send them a Drink", browse_with_contact_gifts_path(id: @gift.giver_id), :class => "btn" %>
    </div>
    <div class="saveLater">
      <%= button_to 'Save for later', gifts_path, method: :get %>
    </div>
    <h2 class="textGive">
      Give this code to your server to redeem:
    </h2>
    <h2 class="redeemCode">
      <a href=""><%= @redeem.redeem_code %></a>
    </h2>
<!--     <h2 class="enterCode">
      Server's phone unavailable? <br />
      <button type="button" id="merchant_redeem">
       Enter Server Code
      </button>
    </h2> -->
  </div>

<div id="server_code_field">
  <%= simple_form_for @order do |f| %>
  <%= f.error_notification %>
  <% if @order.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@order.errors.count, "error") %>.
    </div>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      <% if @order.errors[:server_code] %>
        <li><%= @order.errors[:server_code] %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-horizontal">
    <%= f.hidden_field :redeem_id   %>
    <%= f.hidden_field :gift_id     %>
    <%= f.hidden_field :provider_id %>
    <div>
      <% @server_codes.each do |s| %>
        <h3><%= s %></h3>
      <% end %>
    </div>
    <%= f.input :server_code, :input_html => { :maxlength => 4 } %>
  </div>
  <%= f.submit "Submit Server Code", :class => "btn" %>
  <% end %>

</div>

 