config/routes.rb
Drinkboard::Application.routes.draw do
  
  root to: 'users#new'
  resources :locations

  resources :employees
  match "/invite/:id" => "invite#show"
  
  resources :orders
  resources :redeems
  resources :gifts do
    collection do
      get  'buy'
      get  'activity'
      get  'browse'
      post 'browse_with_contact'
      post 'browse_with_location'
      post 'choose_from_menu'
      post 'choose_from_contacts'
      post 'bill'
      get  'past'
    end
    member do
      get 'detail'
      get 'completed'
    end
  end

  resources :providers 
  
  
  resources :merchants do
    member do
      get 'past_orders'
      get 'detail'
      get 'customers'
      get 'orders'
      get 'order'
      get 'completed'
      get 'staff'
    end
  end
  
  resources :items
  resources :menus
  resources :menu_strings

  resources :connections, only: [:create, :destroy]
  resources :sessions,    only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  resources :admins, only: [:new, :create, :destroy]

  
  match 'app/create_account',   to: 'iphone#create_account',   via: :post
  match 'app/login',            to: 'iphone#login',            via: :post
  match 'app/gifts',            to: 'iphone#gifts',            via: :post
  match 'app/buys',             to: 'iphone#buys',             via: :post
  match 'app/activity',         to: 'iphone#activity',         via: :post
  match 'app/provider',         to: 'iphone#provider',         via: :post
  match 'app/locations',        to: 'iphone#locations',        via: :post
  match 'app/buy_gift',         to: 'iphone#create_gift',      via: :post
  match 'app/redeem',           to: 'iphone#create_redeem',    via: :post
  match 'app/order',            to: 'iphone#create_order',     via: :post
  match 'app/users',            to: 'iphone#drinkboard_users', via: :post
  match 'app/photo',            to: 'iphone#update_photo',     via: :post 
  match 'app/merchant/active',  to: 'iphone#active_orders',    via: :post
  match 'app/merchant/complete',to: 'iphone#completed_orders', via: :post
  
  match '/about',       to: 'home#about'
  match '/contact',     to: 'home#contact'
  match '/home',        to: 'home#index'
  match '/learn',       to: 'home#learn'
  match '/news',        to: 'home#news'
  
  match '/facebook/oauth',    to: 'oAuth#loginWithFacebook'
  match '/foursquare/oauth',  to: 'oAuth#loginWithFoursquare'
  
  match '/map', to: 'locations#map'
  match '/map/boundary', to: 'locations#mapForUserWithinBoundary'
  
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :users do 
    member do
      get :following, :followers
      get :servercode
      get :crop
    end
  end
  

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  
  def index
    @providers = current_user.providers    

    respond_to do |format|
      if @providers.count == 1
        format.html { redirect_to merchant_path(@providers.pop) }
      else
        format.html
      end
    end
  end

  def show
    @provider = Provider.find(params[:id])
    @menu = create_menu_from_items(@provider)
    @gifts = Gift.get_activity_at_provider(@provider)
  end

  def orders
    @provider = Provider.find(params[:id])
    # @gifts = Gift.get_provider(@provider)
    @gifts = Gift.get_all_orders(@provider)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifts }
    end
  end

  def past_orders
    @provider = Provider.find(params[:id])
    @gifts = Gift.get_history_provider(@provider)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifts }
    end
  end

  def detail
    @gift = Gift.find(params[:id])
    @giver = @gift.giver
    @receiver = @gift.receiver
    @provider = @gift.provider
    if @gift.order.server_id
      @server = User.find(@gift.order.server_id) 
    else
      @server = User.new(first_name: "missing", last_name: "person")
    end
    respond_to do |format|
      format.html # detail.html.erb
      format.json { render json: @gift }
    end
  end

  def order
    @gift = Gift.find(params[:id])
    @redeem = Redeem.find_by_gift_id(@gift)
    @provider = @gift.provider
    
    if @redeem
      @order = Order.new(redeem_id: @redeem.id, gift_id: @gift.id, server_id: current_user.id, provider_id: @provider.id)
    else
      # no redeem = no order possible
      @order = Order.new
    end


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @redeem }
    end
  end
  
  def completed
    @order = Order.find(params[:id])
    @gift = @order.gift
    @giver = @gift.giver
    @receiver = @gift.receiver
    @provider = @order.provider
    if @order.server_id
      @server = User.find(@order.server_id) 
    else
      @server = User.new(first_name: "missing", last_name: "person")
    end
    respond_to do |format|
      format.html # detail.html.erb
      format.json { render json: @gift }
    end
  end

  def customers
    @provider = Provider.find(params[:id])    
    @user     = current_user
    @users    = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
    # list customers on the screen with most recent activity first
        # most drinks ordered
        # most money spent
    # check all the gifts , get the giver and receiver user ids
    # assign those ids to the gift.updated_at field 
    # make a uniq array of all user ids
    # remove employees from that list 
    # list those customers on the screen by gift.updated_at
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def staff
    @provider = Provider.find(params[:id])
    @staff    = @provider.users
  end


end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_merchant_redeem.html.erb
<h1>Enter Customer Redeem Code</h1>

<%= simple_form_for @order do |f| %>
  <%= f.error_notification %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@order.errors.count, "error") %>.
      </div>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">
    <%= f.input :redeem_code, :input_html => { :maxlength => 4 } %>
  </div>
    <%= f.submit "Submit", :class => "btn" %>
<% end %>

app/views/merchants/completed.html.erb
<p id="notice"><%= notice %></p>
<div class="borderBox">
  <h2>Thank You!</h2>
  <h3>- The Drinkboard Staff</h3>

  <h4><%= time_ago_in_words(@gift.created_at) %>&nbsp;ago</h4>
  <h4><%= list_icon_for @giver %> <%= @gift.giver_name %><span> bought </span></h4>
  <h4><%= @gift.quantity %> <%= @gift.item_name %></h4>
  <h2>For:</h2>
  <h4><%= list_icon_for @receiver %> <%= @gift.receiver_name %><span></span></h4>
  <h3><%= logo_from_id_for @gift.provider_id %>
  @ <%= @gift.provider_name %></h3>
  <h3>Redeemed on <%= @order.created_at.to_formatted_s(:rfc822)  %>.<br />
  By server : <%= @server.username %></h3>
</div>
<%= link_to "<- Back to Orders", orders_merchant_path(@provider) %>

app/views/merchants/customers.html.erb
<div class="center">
  <table>
    <thead>
      <tr>
        <th colspan="4">Who's About</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= gravatar_for user %></td>
          <td><%= link_to user.username, user %></td>
          <td><%= user.full_address %></td>
          <td><%= number_to_phone user.phone %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/merchants/detail.html.erb
<p id="notice"><%= notice %></p>
<div class="borderBox">
  <h2>Thank You!</h2>
  <h3>- The Drinkboard Staff</h3>

  <h4><%= time_ago_in_words(@gift.created_at) %>&nbsp;ago</h4>
  <h4><%= list_icon_for @giver %> <%= @gift.giver_name %><span> bought </span></h4>
  <h4><%= @gift.quantity %> <%= @gift.item_name %></h4>
  <h2>For:</h2>
  <h4><%= list_icon_for @receiver %> <%= @gift.receiver_name %><span></span></h4>
  <h3><%= logo_from_id_for @gift.provider_id %>
  @ <%= @gift.provider_name %></h3>
  <h3>Redeemed on <%= @gift.order.created_at.to_formatted_s(:rfc822)  %>.<br />
  By server : <%= @server.username %></h3>
</div>
<%= link_to "<- Back to Completed Orders", past_orders_merchant_path(@provider) %>

app/views/merchants/index.html.erb
<h2>Choose Establishment to sign into</h2>
<table>
  <tr>
    <th>Logo</th>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th></th>
  </tr>

  <% @providers.each do |provider| %>
    <tr>
      <td><%= logo_for(provider) %></td>
      <td><%= link_to provider.name, provider %></td>
      <td><%= provider.description %></td>
      <td><%= provider.full_address %></td>
      <td><%= button_to "Log In", merchant_path(provider),method: :get, :class => 'btn btn-large btn-info'%>
      </td>
    </tr>
  <% end %>
</table>

app/views/merchants/menu.html.erb
<div id="menu">
  <table >
    <thead>
      <tr>
        <th>Category</th>
        <th>Name</th>
        <th>Detail</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @menu.each do |m| %>
        <% item = m[0] %>
        <% price = m[1] %>
      <tr>
        <td><%= image_tag get_category_from_item(item), {:class => 'iconListView'} %></td>
        <td><%= item.item_name %></td>
        <td><%= item.detail %></td>
        <td><%= price %></td>
      </tr>
      <% end %>
    </tbody>
  </table>       
</div>

app/views/merchants/order.html.erb
<p id="notice"><%= notice %></p>

<h4><%= list_icon_with_id_for @gift.receiver_id %> <%= @gift.receiver_name %><span> has been gifted </span></h4>
<h4><%= @gift.quantity %> <%= @gift.item_name %></h4>

<% if @redeem %>
  <h1>Enter Customer Redeem Code : <%= @redeem.redeem_code %></h1>

  <%= simple_form_for @order do |f| %>
    <%= f.error_notification %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-error">
          The form contains <%= pluralize(@order.errors.count, "error") %>.
        </div>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-horizontal">
      <%= f.hidden_field :redeem_id  %>
      <%= f.hidden_field :gift_id  %>
      <%= f.hidden_field :server_id  %>
      <%= f.hidden_field :provider_id  %>
      <%= f.input :redeem_code, :input_html => { :maxlength => 4 } %>
    </div>
      <%= f.submit "Submit", :class => "btn" %>
  <% end %>
<% else %>
  <h4>Customer has not Redeemed Gift on their Account yet</h4>
<% end %>
<h4>Your 4-digit Server Code is: 
  <a href="#" class="btn btn-large btn-primary disabled"><%= current_user.server_code || 'please set your server code' %></a>
  <hr />
</h4>

<%= button_to 'Not Now', orders_merchant_path(@provider), method: :get %>

app/views/merchants/orders.html.erb
<%= render 'gifts/index', gifts: @gifts, giver: true %>

app/views/merchants/past_orders.html.erb
<table>
  <tr>
    <th><%= link_to "Active Orders", orders_merchant_path(@provider) %> </th>
    <th colspan="2">To</th>
    <th colspan="2">Drink</th>
    <th>Message</th>
    <th>Redeem Date</th>
    <th colspan="2">From</th>
  </tr>

<% @gifts.each do |gift| %>
  <tr>
    <td><%= button_to "Details", detail_merchant_path(gift), method: :get %></td>
    <td colspan="2">
      <%= list_icon_with_id_for gift.receiver_id %>
      <%= gift.receiver_name %>
    </td>
    <td colspan="2">
      <%= image_tag get_category_image(gift), {:class => 'iconListView'} %>
      <%= gift.quantity %>&nbsp;<%= gift.item_name %>
    </td>
    <td><%= gift.message %></td>
    <td><%= time_ago_in_words(gift.order.created_at) %>&nbsp;ago</td>
    <td colspan="2">
      <%= list_icon_with_id_for gift.giver_id %>
      <%= gift.giver_name %>
    </td>
  </tr>
<% end %>
</table>

app/views/merchants/show.html.erb
<h2><%= @provider.name %></h2>
<%= logo_for @provider %>
<h4><%= @provider.description %></h4>
<h4><%= @provider.full_address %></h4>

<div class="center">
  <ul id="myTab" class="nav nav-tabs">
    <li class="active"><a href="#panel" data-toggle="tab">Navigation</a></li>
    <li><a href="#drinkboard" data-toggle="tab">Drinkboard</a></li>
    <li><a href="#menu" data-toggle="tab">Menu</a></li>
    <li><a href="#activity" data-toggle="tab">Activity</a></li>
  </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="panel">
        <%= link_to "Message Center", '#' %>                       |
        <%= link_to "Customers", customers_merchant_path(@provider) %> |
        <%= link_to "Orders", orders_merchant_path(@provider) %> |
        <%= link_to "Search", '#' %>                               |
        <%= link_to "Reports", '#' %>                              |
        <%= link_to "Staff", staff_merchant_path(@provider) %>                                |
        <%= link_to "Settings", '#' %>
      </div>
      <div class="tab-pane fade" id="drinkboard">

        <%= render 'gifts/index', gifts: @gifts %>


      </div>
      <div class="tab-pane fade" id="activity">
        <p>Recent Activity At Location</p>
      </div>
      <div class="tab-pane fade" id="menu">
        <table class="table listed">
          <thead>
            <tr>
              <th>Category</th>
              <th>Name</th>
              <th>Detail</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            <% @menu.each do |m| %>
              <% item = m[0] %>
              <% price = m[1] %>
            <tr>
              <td><%= image_tag get_category_from_item(item), {:class => 'iconListView'} %></td>
              <td><%= item.item_name %></td>
              <td><%= item.detail %></td>
              <td><%= price %></td>
            </tr>
            <% end %>
          </tbody>
        </table>       
      </div>
    </div>
  </div>

app/views/merchants/staff.html.erb
<div class="center">
  <table>
    <thead>
      <tr>
        <th colspan="4">Staff List</th>
      </tr>
    </thead>
    <tbody>
      <% @staff.each do |user| %>
        <tr>
          <td><%= gravatar_for user %></td>
          <td><%= link_to user.username, user %></td>
          <td><%= user.full_address %></td>
          <td><%= number_to_phone user.phone %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>